In [1]:
# from google.colab import drive
# drive.mount('/content/drive/')

In [3]:
pip install python_speech_features

  Created wheel for python-speech-features: filename=python_speech_features-0.6-py3-none-any.whl size=5892 sha256=5e83adffe0642611fa2fe179a7d8d3f12a7c9c806d9bb596350d0fc694a2f710
  Stored in directory: c:\users\ishaa\appdata\local\pip\cache\wheels\5b\60\87\28af2605138deac93d162904df42b6fdda1dab9b8757c62aa3
Successfully built python-speech-features
Note: you may need to restart the kernel to use updated packages.


In [1]:
from python_speech_features import mfcc
import scipy.io.wavfile as wav
import numpy as np

from tempfile import TemporaryFile
import os
import pickle
import random 
import operator

import math
import numpy as np



In [2]:
def getNeighbors(trainingSet, instance, k):
    distances = []
    for x in range (len(trainingSet)):
        dist = distance(trainingSet[x], instance, k )+ distance(instance, trainingSet[x], k)
        distances.append((trainingSet[x][2], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors



In [3]:
def nearestClass(neighbors):
    classVote = {}

    for x in range(len(neighbors)):
        response = neighbors[x]
        if response in classVote:
            classVote[response]+=1 
        else:
            classVote[response]=1

    sorter = sorted(classVote.items(), key = operator.itemgetter(1), reverse=True)
    return sorter[0][0]



In [4]:
def getAccuracy(testSet, predictions):
    correct = 0 
    for x in range (len(testSet)):
        if testSet[x][-1]==predictions[x]:
            correct+=1
    return 1.0*correct/len(testSet)



In [17]:
directory = "./Music/genres"
f= open("my.dat" ,'wb')
i=0

for folder in os.listdir(directory):
    i+=1
    print(i)
    if i==11 :
        break 
    for file in os.listdir(directory+"/"+folder):
        (rate,sig) = wav.read(directory+"/"+folder+"/"+file)
        mfcc_feat = mfcc(sig,rate ,winlen=0.020, appendEnergy = False)
        covariance = np.cov(np.matrix.transpose(mfcc_feat))
        mean_matrix = mfcc_feat.mean(0)
        feature = (mean_matrix , covariance , i)
        pickle.dump(feature , f)

f.close()



1
2
3
4
5
6
7
8
9
10


In [5]:
dataset = []
def loadDataset(filename , split , trSet , teSet):
    with open("my.dat" , 'rb') as f:
        while True:
            try:
                dataset.append(pickle.load(f))
            except EOFError:
                f.close()
                break

    for x in range(len(dataset)):
        if random.random() <split :
            trSet.append(dataset[x])
        else:
            teSet.append(dataset[x])

trainingSet = []
testSet = []
loadDataset("my.dat" , 0.66, trainingSet, testSet)


In [6]:
def distance(instance1 , instance2 , k ):
    distance =0 
    mm1 = instance1[0] 
    cm1 = instance1[1]
    mm2 = instance2[0]
    cm2 = instance2[1]
    distance = np.trace(np.dot(np.linalg.inv(cm2), cm1)) 
    distance+=(np.dot(np.dot((mm2-mm1).transpose() , np.linalg.inv(cm2)) , mm2-mm1 )) 
    distance+= np.log(np.linalg.det(cm2)) - np.log(np.linalg.det(cm1))
    distance-= k
    return distance


# Finding Accuracy

In [7]:
leng = len(testSet)
predictions = []
for x in range (leng):
    if(x%10)
        print(x)
    predictions.append(nearestClass(getNeighbors(trainingSet ,testSet[x] , 5))) 

accuracy1 = getAccuracy(testSet , predictions)
print(accuracy1)


SyntaxError: invalid syntax (<ipython-input-7-70f0c2df0e05>, line 4)

# Importing stuff

In [8]:
from python_speech_features import mfcc
import scipy.io.wavfile as wav
import numpy as np
from tempfile import TemporaryFile
import os
import pickle
import random 
import operator

import math
import numpy as np
from collections import defaultdict

# Compiling everything at one place

In [9]:

dataset = []
def loadDataset(filename):
    with open("my.dat" , 'rb') as f:
        while True:
            try:
                dataset.append(pickle.load(f))
            except EOFError:
                f.close()
                break

loadDataset("my.dat")

def distance(instance1 , instance2 , k ):
    distance =0 
    mm1 = instance1[0] 
    cm1 = instance1[1]
    mm2 = instance2[0]
    cm2 = instance2[1]
    distance = np.trace(np.dot(np.linalg.inv(cm2), cm1)) 
    distance+=(np.dot(np.dot((mm2-mm1).transpose() , np.linalg.inv(cm2)) , mm2-mm1 )) 
    distance+= np.log(np.linalg.det(cm2)) - np.log(np.linalg.det(cm1))
    distance-= k
    return distance

def getNeighbors(trainingSet , instance , k):
    distances =[]
    for x in range (len(trainingSet)):
        dist = distance(trainingSet[x], instance, k )+ distance(instance, trainingSet[x], k)
        distances.append((trainingSet[x][2], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors

def nearestClass(neighbors):
    classVote ={}
    for x in range(len(neighbors)):
        response = neighbors[x]
        if response in classVote:
            classVote[response]+=1 
        else:
            classVote[response]=1 
    sorter = sorted(classVote.items(), key = operator.itemgetter(1), reverse=True)
    return sorter[0][0]

results=defaultdict(int)

i=1
for folder in os.listdir("./Music/genres"):
    results[i]=folder
    i+=1

(rate,sig)=wav.read("./Music/genres/blues/blues.00071.wav")
mfcc_feat=mfcc(sig,rate,winlen=0.020,appendEnergy=False)
covariance = np.cov(np.matrix.transpose(mfcc_feat))
mean_matrix = mfcc_feat.mean(0)
feature=(mean_matrix,covariance,0)

pred=nearestClass(getNeighbors(dataset ,feature , 5))

print(results[pred])

blues


# Random Data Exploration 

In [10]:
print(results)

defaultdict(<class 'int'>, {1: 'blues', 2: 'classical', 3: 'country', 4: 'disco', 5: 'hiphop', 6: 'jazz', 7: 'metal', 8: 'pop', 9: 'reggae', 10: 'rock'})


In [11]:
# Data Exploration
for i in range (70,73):
    print("./Music/genres/blues/blues.000"+ str(i) +".wav")
    (rate,sig)=wav.read("./Music/genres/blues/blues.000"+ str(i) +".wav")
    print(rate)
    print(sig,sig.shape)
    print()


./Music/genres/blues/blues.00070.wav
22050
[-1252 -2045 -2073 ...  1272   822   197] (661794,)

./Music/genres/blues/blues.00071.wav
22050
[ -820 -5094 -7456 ...  -290  -411 -1802] (661794,)

./Music/genres/blues/blues.00072.wav
22050
[1373 3702 5015 ...  807  517  423] (661794,)



In [12]:
file = "blues.00003.wav"
f = get_data(file)
print(type(f))

print(len(dataset))

NameError: name 'get_data' is not defined

# Function to load the uploaded file from Flask app

In [13]:
def get_data(filename):
    (rate,sig)=wav.read(filename)
    mfcc_feat=mfcc(sig,rate,winlen=0.020,appendEnergy=False)
    covariance = np.cov(np.matrix.transpose(mfcc_feat))
    mean_matrix = mfcc_feat.mean(0)
    feature=(mean_matrix,covariance,0)
    return feature


# Flask App

In [30]:
pip install flask_cors

Note: you may need to restart the kernel to use updated packages.


In [16]:
from flask import Flask, render_template, request, jsonify
import base64
from flask_cors import CORS, cross_origin

app = Flask(__name__, template_folder="templates")
cors = CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'

@app.route('/',methods=['GET'])
def main_page():
    return render_template('index.html')

# @app.route('/upload')
# def upload_file():
#     return render_template('upload.html')

@app.route('/uploader', methods = ['GET', 'POST'])
@cross_origin()
def upload_file():
    print("got req")
    print("request",request)
    print("request.form",request.form)
#     print("request.form['music']",request.form['music'])
    
    print("request.files",request.files)
                                                                
    if request.method == 'POST':
        print("got post req")
        print(request.files)
        f = request.files['music'] 
        print("type(f)",type(f))
        print("f.filename",f.filename)
        f.save(f.filename)  
        print("file saved")
        
        filename = f.filename        
        prediction = "Error | feature = None"
        feature = None
        try:
            feature = get_data(str(filename))
            if feature!=None:
                c=1
                prediction = nearestClass(getNeighbors(dataset ,feature , 5))
                c=1
        except:
            print(prediction)
            return render_template('index.html',response="Ran Into error", success=False)
        
        print(results[prediction])
        return render_template('index.html',response=str(results[prediction]), success=True)
    
    return render_template('index.html',response=str(prediction), success=False)


In [ ]:
app.run(port = 5000)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [24/Aug/2021 17:46:32] "GET / HTTP/1.1" 200 -


got req
request <Request 'http://127.0.0.1:5000/uploader' [POST]>
request.form ImmutableMultiDict([])
request.files ImmutableMultiDict([('music', <FileStorage: 'blues.00003.wav' ('audio/wav')>)])
got post req
ImmutableMultiDict([('music', <FileStorage: 'blues.00003.wav' ('audio/wav')>)])
type(f) <class 'werkzeug.datastructures.FileStorage'>
f.filename blues.00003.wav
file saved


127.0.0.1 - - [24/Aug/2021 17:46:46] "POST /uploader HTTP/1.1" 200 -


blues
